export const sectoralIndicesCap = [
  'Nifty AUTO',
  'NIFTY FINANCIAL SERVICES 25/50',
  'NIFTY FMCG',
  'NIFTY IT',
  'NIFTY MEDIA',
  'NIFTY METAL',
  'NIFTY PHARMA',
  'NIFTY PSU BANK',
  'NIFTY PRIVATE BANK',
  'NIFTY REALTY',
  'NIFTY HEALTHCARE INDEX',
  'NIFTY CONSUMER DURABLES',
  'NIFTY OIL & GAS',
  'NIFTY MIDSMALL HEALTHCARE',
  'NIFTY FINANCIAL SERVICES EX-BANK',
  'NIFTY MIDSMALL FINANCIAL SERVICES',
  'NIFTY MIDSMALL IT & TELECOM',
];

export const sectoralIndices = [
  'Automobiles',
  'Financial Services',
  'FMCG',
  'Information Technology',
  'Media',
  'Metals & Mining',
  'Pharmaceuticals & Healthcare',
  'Real Estate',
  'Consumer Durables',
  'Oil & Gas',
  'Cement',
  'Power',
  'Construction & Infrastructure',
  'Chemicals',
  'Telecommunications',
  'Capital Goods & Electrical Equipment',
  'Retail',
  'Logistics',
  'Aerospace & Defense',
  'Building Materials',
  'Agro Chemicals',
  'Financial Market Infrastructure',
  'Jewellery',
  'Diversified',
  'Steel Tubes & Pipes',
];
